export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const DETAIL_SCREEN = 'DETAIL_SCREEN';
export const UNIVERSITIES_SCREEN = 'UNIVERSITIES_SCREEN';
export const DETAIL_UNIVERSITY = 'DETAIL_UNIVERSITY';
